definitions:
  Hello:
    properties:
      greet:
        type: "string"
      language:
        type: "string"
/api/hello:
  # list
  get:
    tags:
      - "Hello"
    description: "Returns all hello"
    produces:
      - "application/json"
    responses:
      200:
        description: "An array of Hello"
        schema:
          type: "array"
          items:
            $ref: "#/definitions/Hello"
      500:
        description: "Invalid status value"
  # create
  post:
    tags:
      - "Hello"
    description: "Creates a new Hello"
    produces:
      - "application/json"
    parameters:
      - in: "body"
        name: "body"
        description: "Hello's greet"
        required: true
        schema:
          $ref: "#/definitions/Hello"
    responses:
      200:
        description: "object Hello created"
/api/hello/{id}:
  # read
  get:
    tags:
      - "Hello"
    description: "Returns a single Hello"
    produces:
      - "application/json"
    parameters:
      - name: "id"
        description: "Hello's id"
        in: "path"
        required: true
        type: "string"
    responses:
      200:
        description: "A single Hello"
        schema:
          $ref: "#/definitions/Hello"
  # update
  put:
    tags:
      - "Hello"
    description: "Updates a single Hello"
    produces:
      - "application/json"
    parameters:
      - name: "id"
        description: "Hello's id"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Fields for the Hello resource"
        schema:
          type: "array"
          $ref: "#/definitions/Hello"
    responses:
      200:
        description: "object Hello updated"
  # remove
  delete:
    tags:
      - "Hello"
    description: "Deletes a single Hello"
    produces:
      - "application/json"
    parameters:
      - name: "id"
        description: "Hello's id"
        in: "path"
        required: true
        type: "string"
    responses:
      200:
        description: "object deleted"
