definitions:
  User:
    properties:
      username:
        type: "string"
      password:
        type: "string"
      email:
        type: "string"
      name:
        type: "string"
      lastname:
        type: "string"
      photo:
        type: "string"
      provider:
        type: "string"
      roles:
        type: "array"
      status:
        type: "number"
      date:
        type: "string"
      last_login:
        type: "string"
      social:
        type: "object"
/api/user:
  # list
  get:
    tags:
      - "User"
    description: "Returns list of Users"
    produces:
      - "application/json"
    responses:
      200:
        description: "An array of User"
        schema:
          type: "array"
          items:
            $ref: "#/definitions/User"
      401:
        description: "Error Unauthorized"
    security:
      - Bearer: []
  # create
  post:
    tags:
      - "User"
    description: "Creates a new User"
    produces:
      - "application/json"
    parameters:
      - in: "body"
        name: "body"
        description: "Create new User"
        required: true
        schema:
          $ref: "#/definitions/User"
    responses:
      200:
        description: "Result"
/api/user/{id}:
  # read
  get:
    tags:
      - "User"
    description: "Returns a single User"
    produces:
      - "application/json"
    parameters:
      - name: "id"
        description: "User's id"
        in: "path"
        required: true
        type: "string"
    responses:
      200:
        description: "A single User"
        schema:
          $ref: "#/definitions/User"
    security:
      - Bearer: []
  # remove
  delete:
    tags:
      - "User"
    description: "Deletes a single User"
    produces:
      - "application/json"
    parameters:
      - name: "id"
        description: "User's id"
        in: "path"
        required: true
        type: "string"
    responses:
      200:
        description: "Result Operation"
    security:
      - Bearer: []
/api/user/me:
  # me
  get:
    tags:
      - "User"
    description: "Returns session User"
    produces:
      - "application/json"
    responses:
      200:
        description: "An array of User"
        schema:
          $ref: "#/definitions/User"
      401:
        description: "Error Unauthorized"
    security:
      - Bearer: []
