definitions:
  User:
    properties:
      username:
        type: "string"
      password:
        type: "string"
      email:
        type: "string"
      name:
        type: "string"
      lastname:
        type: "string"
      photo:
        type: "string"
      provider:
        type: "string"
      roles:
        type: "array"
        items:
          type: "string"
      status:
        type: "number"
      date:
        type: "string"
      last_login:
        type: "string"
      social:
        type: "object"
/api/v1/user:
  # list
  get:
    tags:
      - "User"
    summary: "Get list users [Rol admin]"
    description: "Returns list of Users"
    produces:
      - "application/json"
    responses:
      200:
        description: "An array of User"
        schema:
          type: "array"
          items:
            $ref: "#/definitions/User"
      401:
        description: "Error Unauthorized"
      403:
        description: "Rol Unauthorized"
      500:
        description: "Error"
    security:
      - Bearer: []
  # create
  post:
    tags:
      - "User"
    summary: "Create user"
    description: "Creates a new User"
    produces:
      - "application/json"
    parameters:
      - in: "body"
        name: "body"
        description: "Create new User"
        required: true
        schema:
          $ref: "#/definitions/User"
    responses:
      200:
        description: "Result"
      500:
        description: "Error"
  # update
  put:
    tags:
      - "User"
    summary: "Update current user [Signed]"
    description: "update a single User"
    produces:
      - "application/json"
    parameters:
      - in: "body"
        name: "body"
        description: "Fields for the User resource"
        schema:
          type: "array"
          $ref: "#/definitions/User"
    responses:
      200:
        description: "Result Operation"
      401:
        description: "Error Unauthorized"
      500:
        description: "Error"
    security:
      - Bearer: []
/api/v1/user/{id}:
  # read
  get:
    tags:
      - "User"
    summary: "Get user by id [Signed]"
    description: "Returns a single User"
    produces:
      - "application/json"
    parameters:
      - name: "id"
        description: "User's id"
        in: "path"
        required: true
        type: "string"
    responses:
      200:
        description: "A single User"
        schema:
          $ref: "#/definitions/User"
      401:
        description: "Error Unauthorized"
      500:
        description: "Error"
    security:
      - Bearer: []
  # remove
  delete:
    tags:
      - "User"
    summary: "Delete user by id [Rol admin]"
    description: "Deletes a single User"
    produces:
      - "application/json"
    parameters:
      - name: "id"
        description: "User's id"
        in: "path"
        required: true
        type: "string"
    responses:
      200:
        description: "Result Operation"
      401:
        description: "Error Unauthorized"
      403:
        description: "Rol Unauthorized"
      500:
        description: "Error"
    security:
      - Bearer: []
  # update
  put:
    tags:
      - "User"
    summary: "Update user by id [Rol admin]"
    description: "update a single User"
    produces:
      - "application/json"
    parameters:
      - name: "id"
        description: "User's id"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Fields for the User resource"
        schema:
          type: "array"
          $ref: "#/definitions/User"
    responses:
      200:
        description: "Result Operation"
      401:
        description: "Error Unauthorized"
      403:
        description: "Rol Unauthorized"
      500:
        description: "Error"
    security:
      - Bearer: []
/api/v1/user/me:
  # me
  get:
    tags:
      - "User"
    summary: "Get current user [Signed]"
    description: "Returns session User"
    produces:
      - "application/json"
    responses:
      200:
        description: "An array of User"
        schema:
          $ref: "#/definitions/User"
      401:
        description: "Error Unauthorized"
      500:
        description: "Error"
    security:
      - Bearer: []
